// Spizarnia-react/src/components/pages/manage/Manage.tsx
import React from "react";
import { NavLink, Outlet } from "react-router-dom";

function classNameSelectorNavButton(isActive : boolean)
{
    return isActive ? "active-link" : "action-button"
}

function Manage() {
    return (
        <>        
        <div className="manage-header-container">
            <div className="title">Zarządzaj</div>
                <div className="button-group">
                    <NavLink to="/manage/productModelView" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Zarządzaj produktami w katalogu</NavLink >
                    <NavLink to="/manage/productModel" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Dodaj produkt do katalogu</NavLink >
                    <NavLink to="/manage/product" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Dodaj produkt do spiżarni</NavLink >
                    <NavLink to="/manage/recipe" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Dodaj przepis</NavLink >
                    <NavLink to="/manage/category" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Dodaj kategorię</NavLink >
                </div>
        </div>

        <div className="site-content">
            <Outlet />
        </div>    
        </>
    );
}

export default Manage

// Spizarnia/src/app/components/pages/manage/manage.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';


@Component({
  selector: 'app-manage',
  imports: [RouterModule],
  templateUrl: './manage.component.html',
  styleUrl: './manage.component.css'
})
export class ManageComponent {

}

<div class="manage-header-container">
  <div class="title">Zarządzaj</div>
  <div class="button-group">
    <a [routerLink]="['/manage/productModelView']" class="action-button" routerLinkActive="active-link">Zarządzaj produktami w katalogu</a>
    <a [routerLink]="['/manage/productModel']" class="action-button" routerLinkActive="active-link">Dodaj produkt do katalogu</a>
    <a [routerLink]="['/manage/product']" class="action-button" routerLinkActive="active-link">Dodaj produkt do spiżarni</a>
    <a [routerLink]="['/manage/recipe']" class="action-button" routerLinkActive="active-link">Dodaj przepis</a>
    <a [routerLink]="['/manage/category']" class="action-button" routerLinkActive="active-link">Dodaj kategorię</a>
  </div>
</div>

<!-- Wyświetlanie dynamicznego widoku -->
<div class="site-content">
  <router-outlet></router-outlet>
</div>
