// Spizarnia/src/app/components/partials/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  imports: [],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  isPantryVisible = false;
  isShoppingListVisible = false;

  toggleSection(section: string): void {
    if (section === 'pantry') {
      this.isPantryVisible = !this.isPantryVisible;
    } else if (section === 'shoppingList') {
      this.isShoppingListVisible = !this.isShoppingListVisible;
    }
  }
  managePantry(): void {
    console.log('Zarządzaj funkcja kliknięta');
    // Dodaj logikę do zarządzania spiżarnią.
  }

  browsePantry(): void {
    console.log('Przeglądaj funkcja kliknięta');
    // Dodaj logikę do przeglądania spiżarni.
  }
}

<header>
  <div class="header-container">
    <div class="title-section">
      <div class="header-title">
        <a [routerLink]="['/home']" routerLinkActive="header-active">Spiżarnia domowa</a>
      </div>
    </div>
    <div class="button-section">
      <a [routerLink]="['/all-products']" class="action-button" routerLinkActive="active-link">Moja Spizarnia</a>
      <a [routerLink]="['/manage']" class="action-button" routerLinkActive="active-link">Zarządzaj</a>
      <a [routerLink]="['/recipes']" class="action-button" routerLinkActive="active-link">Przepisy</a>
      <a [routerLink]="['/grocery-list']" class="action-button" routerLinkActive="active-link">Lista Zakupów</a>
    </div>
  </div>
</header>

// Spizarnia-react/src/components/partials/Header.tsx
import React from "react";
import {NavLink} from "react-router-dom";

function classNameSelectorTitleButton(isActive : boolean)
{
    return isActive ? "header-active" : ""
}

function classNameSelectorNavButton(isActive : boolean)
{
    return isActive ? "active-link" : "action-button"
}

const Header = () => 
    {
        return (
            <div className="header-container">
                <div className="title-section">
                    <div className="header-title">
                        <NavLink to="/" className={({ isActive }) => classNameSelectorTitleButton(isActive)}>Spiżarnia domowa</NavLink >
                    </div>
                </div>
            <div className="button-section">
                <NavLink to="/all-products" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Moja Spizarnia</NavLink >
                <NavLink to="/manage" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Zarządzaj</NavLink >
                <NavLink to="/recipes" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Przepisy</NavLink >
                <NavLink to="/grocery-list" className={({ isActive }) => classNameSelectorNavButton(isActive)}>Lista Zakupów</NavLink >

            </div>
        </div>
        )
    }

export default Header;
